<?php

/**
 * @file
 * Ut_feature module install file.
 */

/**
 * Reset all paragraph fields to match standard config.
 */
function ut_feature_update_8001() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'ut_feature');
}

/**
 * Remove required on style and color fields.
 */
function ut_feature_update_8002() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'ut_feature');
}
