<?php

/**
 * @file
 * Ut_slideshow module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function ut_slideshow_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.ut_slideshow':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 *
 * Lets us define our paragraphs templates in this module.
 */
function ut_slideshow_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__ut_slideshow' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__ut_slideshow_item' => [
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_preprocess_paragraph().
 *
 *   This sets the total number of slides.
 */
function ut_slideshow_preprocess_paragraph__ut_slideshow(&$variables) {
  if (isset($variables['elements']['#paragraph']->field_ut_slideshow_items)) {
    $length = $variables['elements']['#paragraph']->field_ut_slideshow_items->getValue();
    $variables['ut_slideshow_length'] = count($length);
  }
}

/**
 * Implements hook_field_WIDGET_TYPE_paragraphs_form_alter().
 *
 * Adds "Content Tips" helper text to the paragraph.
 */
function ut_slideshow_field_widget_paragraphs_form_alter(&$element, &$form_state, $context) {
  if ($element['#paragraph_type'] == 'ut_slideshow') {
    // Tips text.
    $markup = '<ul>';
    $markup .= '<li><strong>Use at least three images.</strong> If you only have one or two images, consider using a different widget.</li>';
    $markup .= '<li><strong>Use plain text.</strong> The Caption, Title, and Text should not have styles (bold, italics, etc.).</li>';
    $markup .= '<li><a target="_blank" href="/admin/help/ut_slideshow">Slideshow Help</a></li>';
    $markup .= '</ul>';
    $element['ut_slideshow_tips'] = [
      '#type' => 'details',
      '#title' => t('Slideshow Notes'),
      '#weight' => -1000,
    ];
    $element['ut_slideshow_tips']['#markup'] = $markup;
  }
}
