<?php

/**
 * @file
 * Ut_carousel module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function ut_carousel_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.ut_carousel':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 *
 * Lets us define our paragraphs templates in this module.
 */
function ut_carousel_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__ut_carousel' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__ut_carousel_item' => [
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_field_WIDGET_TYPE_paragraphs_form_alter().
 *
 * Adds "Content Tips" helper text to the paragraph.
 */
function ut_carousel_field_widget_paragraphs_form_alter(&$element, &$form_state, $context) {
  if ($element['#paragraph_type'] == 'ut_carousel') {
    // Tips text.
    $markup = '<ul>';
    $markup .= '<li><strong>Use at least four images.</strong> If you only have less than four then consider using a different widget.</li>';
    $markup .= '<li><a target="_blank" href="/admin/help/ut_carousel">Carousel Help</a></li>';
    $markup .= '</ul>';

    $element['ut_carousel_tips'] = [
      '#type' => 'details',
      '#title' => t('Carousel Notes'),
      '#weight' => -1000,
    ];
    $element['ut_carousel_tips']['#markup'] = $markup;
  }
}
