<?php

/**
 * @file
 * Ut_stats module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function ut_stats_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.ut_stats':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 *
 * Lets us define our paragraphs templates in this module.
 */
function ut_stats_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__ut_stat' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__ut_stat_group' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__field_ut_stat_group_stats' => [
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_field_WIDGET_TYPE_paragraphs_form_alter().
 *
 * Adds "Content Tips" helper text to the paragraph.
 */
function ut_stats_field_widget_paragraphs_form_alter(&$element, &$form_state, $context) {
  if ($element['#paragraph_type'] == 'ut_stat_group') {
    // Tips text.
    $markup = '<ul>';
    $markup .= '<li><strong>Use five characters or less for each stat.</strong> Statistics in the thousands may not display well on small screens.</li>';
    $markup .= '<li>Limit the description to a brief phrase or sentence.</li>';
    $markup .= '<li><a target="_blank" href="/admin/help/ut_stats">Stats Module Help</a></li>';
    $markup .= '</ul>';
    $element['ut_stats_tips'] = [
      '#type' => 'details',
      '#title' => t('Stats Notes'),
      '#weight' => -1000,
    ];
    $element['ut_stats_tips']['#markup'] = $markup;
  }
}
