<?php

/**
 * @file
 * Ut_sidebar module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function ut_sidebar_menu_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.ut_sidebar':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 *
 * This hook defines the template.
 * also need to reference this in hook_block_view()
 */
function ut_sidebar_menu_theme($existing, $type, $theme, $path) {
  $theme = [];
  $theme['umd_terp_sidebar_menu__main'] = [
    'base hook' => 'menu',
    'render element' => 'menu',
  ];
  $theme['block__umd_terp_sidebar_menu'] = [
    'base hook' => 'block',
    'render element' => 'block',
  ];
  return $theme;
}
