<?php

/**
 * @file
 * Ut_button module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function ut_blockquote_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.ut_blockquote':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 *
 * Lets us define our paragraphs templates in this module.
 */
function ut_blockquote_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__ut_blockquote' => [
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_field_WIDGET_TYPE_paragraphs_form_alter().
 *
 * Adds "Content Tips" helper text to the paragraph.
 */
function ut_blockquote_field_widget_paragraphs_form_alter(&$element, &$form_state, $context) {
  if ($element['#paragraph_type'] == 'ut_blockquote') {
    // Tips text.
    $markup = '<ul>';
    $markup .= '<li><strong>Use blockquotes to break up long copy.</strong> A brief quote can provide visual interest and offset larger text blocks.</li>';
    $markup .= '<li><strong>Use plain text.</strong> Avoid including links or other styled elements.</li>';
    $markup .= '<li><strong>Do not place a blockquote as the last element on the page.</strong></li>';
    $markup .= '<li><a target="_blank" href="/admin/help/ut_blockquote">Blockquote Module Help</a></li>';
    $markup .= '</ul>';

    $element['ut_blockquote_tips'] = [
      '#type' => 'details',
      '#title' => t('Blockquote Content Tips'),
      '#weight' => -1000,
    ];
    $element['ut_blockquote_tips']['#markup'] = $markup;
  }
}
