<?php

/**
 * @file
 * Ut_card module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function ut_card_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.ut_card':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 *
 * Lets us define our paragraphs templates in this module.
 */
function ut_card_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__ut_card' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__ut_card_group' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__field_ut_card_group_cards' => [
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_preprocess_paragraph().
 *
 * This preproccess gets the column numbers of parent group.
 */
function ut_card_preprocess_paragraph__ut_card(&$variables) {
  $variables['ut_card_columns'] = $variables['elements']['#paragraph']->getParentEntity()->field_ut_card_group_columns->value;
}

/**
 * Implements hook_field_WIDGET_TYPE_paragraphs_form_alter().
 *
 * Adds "Content Tips" helper text to the paragraph.
 */
function ut_card_field_widget_paragraphs_form_alter(&$element, &$form_state, $context) {
  if ($element['#paragraph_type'] == 'ut_card_group') {
    // Tips text.
    $markup = '<ul>';
    $markup .= '<li><strong>Use two or more cards.</strong> Two cards appear in a two-column grid; three or more cards appear in a three-column grid.</li>';
    $markup .= '<li><strong>Use plain text.</strong>Title and Text should not have styles (bold, italics, etc.).</li>';
    $markup .= '<li><a target="_blank" href="/admin/help/ut_card">Card Module Help</a></li>';
    $markup .= '</ul>';

    $element['ut_card_tips'] = [
      '#type' => 'details',
      '#title' => t('Card Content Tips'),
      '#weight' => -1000,
    ];
    $element['ut_card_tips']['#markup'] = $markup;
  }
}
