<?php

/**
 * @file
 * Ut_tabs module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function ut_tabs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.ut_tabs':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 *
 * Lets us define our paragraphs templates in this module.
 */
function ut_tabs_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__ut_tabs' => [
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_field_WIDGET_TYPE_paragraphs_form_alter().
 *
 * Adds "Content Tips" helper text to the paragraph.
 */
function ut_tabs_field_widget_paragraphs_form_alter(&$element, &$form_state, $context) {
  if ($element['#paragraph_type'] == 'ut_tabs') {
    // Tips text.
    $markup = '<p>Group related information in a series of tabs.</p>';
    $markup = '<ul>';
    $markup .= '<li><strong>Always create two or more tabs.</strong> Use brief, descriptive phrases for each label.</li>';
    $markup .= '<li><strong>Minimize embedded images and tables.</strong> If you’re adding a lot of content to a tab, consider using a different widget. </li>';
    $markup .= '<li><a target="_blank" href="/admin/help/ut_tabs">Tabs Module Help</a></li>';
    $markup .= '</ul>';
    $element['ut_tabs_tips'] = [
      '#type' => 'details',
      '#title' => t('Tabs Content Tips'),
      '#weight' => -1000,
    ];
    $element['ut_tabs_tips']['#markup'] = $markup;
  }
}
