<?php

/**
 * @file
 * Ut_video module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function ut_video_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.ut_video':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 *
 * Lets us define our paragraphs templates in this module.
 */
function ut_video_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__ut_video' => [
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_field_WIDGET_TYPE_paragraphs_form_alter().
 *
 * Adds "Content Tips" helper text to the paragraph.
 */
function ut_video_field_widget_paragraphs_form_alter(&$element, &$form_state, $context) {
  if ($element['#paragraph_type'] == 'ut_video') {
    // Tips text.
    $markup = '<ul>';
    $markup .= '<li><strong>Embed YouTube videos only.</strong> Find your video on youtube.com, then:<ul><li>click <em>Share</em>,</li><li>click <em>Embed</em>,</li><li>copy and paste the <em>src</em> link referenced in the code.</li>';
    $markup .= '<li><strong>Use plain text.</strong> The Title and Caption should not have styles (bold, italics, etc.).</li>';
    $markup .= '<li><a target="_blank" href="/admin/help/ut_video">Video Module Help</a></li>';
    $markup .= '</ul>';

    $element['ut_video_tips'] = [
      '#type' => 'details',
      '#title' => t('Video Content Tips'),
      '#weight' => -1000,
    ];
    $element['ut_video_tips']['#markup'] = $markup;
  }
}
